repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: insert-license
        files: \.py$
        args:
          - --license-filepath=LICENSE_HEADER.txt
          - --comment-style=#
  - repo: local
    hooks:
      - id: black-format
        name: black .
        entry: pdm run black .
        language: system
        pass_filenames: false
        require_serial: true
      - id: pdm-verify
        name: pdm run verify
        entry: pdm run verify
        language: system
        pass_filenames: false
        always_run: true
        require_serial: true
